#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org
 
START=99
STOP=15
USE_PROCD=1
PROG=/usr/bin/aggregation/aggregation

error() {
	echo "${initscript}:" "$@" 1>&2
}               
 
start_service() {

	procd_open_instance
	procd_set_param respawn 
	procd_set_param command "$PROG" -mucfg /usr/bin/aggregation/monitoring-units.json -setcfg /usr/bin/aggregation/index-setting.json -eldir /usr/bin/aggregation/element-lib -alog /tmp/appserver.log -bcfg /usr/bin/aggregation/busmanager.json -blog /tmp/busserver.log -plog /tmp/portserver.log
	procd_close_instance

}

stop_service() {  
        killall "$PROG"
} 

restart() {  
    stop  
    start  
}

